#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*
sed -i '/errorfile 504/a ' /etc/haproxy/haproxy.cfg
sed -i '/         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 23038-web-01 3.230.169.183:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 23038-web-01 3.230.169.183:80 check/a         server 23038-web-02 35.173.47.137:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start