#!/usr/bin/env bash
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

FILE="School"

if [ -e "$FILE" ]
then
    echo "School file exists"
    if [ ! -s "$FILE" ]
    then
        echo "School file is empty"
    else
        echo "School file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
